stages:
  - build
  - paks

variables:
  GIT_SUBMODULE_STRATEGY: recursive
# variables:
  # pkgver: $PKGVER => not parsed by PKGBUILD
  # pkgrel: $PKGREL => not parsed by PKGBUILD
  # AARCH64: $AARCH64
  # X86_64: $X86_64

.carch_aarch64: &carch_aarch64
  variables:
    CARCH: 'aarch64'

.carch_x86_64: &carch_x86_64
  variables:
    CARCH: 'x86_64'

.arch_build_config: &arch_build_config
  stage: build
  script:
    - ./ci.build.sh
  artifacts:
    name: "Librewolf-Arch-${pkgver}-${pkgrel}-${CARCH}"
    paths:
      - "librewolf-${pkgver}-${pkgrel}-${CARCH}*.pkg.tar*"

arch_x86_64:
  image: archlinux/archlinux:base-devel
  tags:
    - docker
    - linux
  <<: *carch_x86_64
  <<: *arch_build_config
  only:
    variables:
      - $X86_64

arch_aarch64:
  image: registry.gitlab.com/ohfp/manjaro-arm-docker
  tags: [aarch64b]
  <<: *carch_aarch64
  <<: *arch_build_config
  only:
    variables:
      - $AARCH64
