on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: git@gitlab.com:librewolf-community/browser/arch.git
        token: ${{ secrets.GITLAB_TOKEN }}

    - name: Push to GitHub
      run: |
        git remote add origin git@github.com:redtrillix/librewolf-arch.git
        git push -u origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
